[project]
name = "morphology"
version = "0.1.0"
description = "Provider for the morphology API for grammr-serverless"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
    "spacy>=3.8.11",
]

[dependency-groups]
dev = [
    "pip>=25.3",
    "pytest>=9.0.2",
]
